### ISSUE TITLE
[Minor] Image not rendered is post cards

### ISSUE THREAD

**Issue by changz23-1836696** [info442-sp21/d-team#100]
**Describe the bug**
In the view event card, the image of the event is not correctly rendered.

**To Reproduce**
1. Go to 'Home'
2. Click on 'View Detail'
3.The event detail shows up

**Expected behavior**
render the correct image or modify the card to fit posts that do not have a image

**Screenshots**
![(122)](https://user-images.githubusercontent.com/43832007/119599579-21866080-bd9a-11eb-9508-4dc049ffcfe2.png)
![image](https://user-images.githubusercontent.com/43832007/119602135-5fd24e80-bd9f-11eb-95d3-223b67941145.png)

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser Chrome
 - Version  90.0.4430.212

**Smartphone (please complete the following information):**
 - Device: iPhone8
 - OS: iOS 14.4.1
 - Browser Chrome

**Comment by ashshah1** [comment]
We are unable to reproduce this bug, we see the same thing on the newsfeed but in our backend it does not look like these users uploaded an image when they created their events. We'll run some more tests to confirm that this was simply a user issue and not a larger bug with file uploads.

**Comment by ashshah1** [comment]
Bug has been fixed: https://github.com/info442-sp21/d-team/commit/487f380760bc82c63743db835f65c38a883af0c0
