### ISSUE TITLE
Users can upload event with a past date[Minor]

### ISSUE THREAD

**Issue by changz23-1836696** [info442-sp21/d-team#101]
**Describe the bug**
When the user creating an event, they can set the date of the event to be on a date before the current date and still able to submit the host. 

**To Reproduce**
1. Go to 'Host an event'
2. Post an event with a date in the past
3. Submit 
4. Go to 'home'
5. See the event with a past date

**Expected behavior**
Stop uploading if the date is impropriated and show an error message.
Not allow users to select previous data on the date selector

**Screenshots**
![image](https://user-images.githubusercontent.com/43832007/119600624-44197900-bd9c-11eb-9177-ce80860b88d6.png)

**Desktop (please complete the following information):**
OS: Windows10
Browser Chrome
Version 90.0.4430.212

**Smartphone (please complete the following information):**
Device: iPhone8
OS: iOS 14.4.1
Browser Chrome

**Comment by ashshah1** [comment]
This is a duplicate bug, we will be addressing the original one here: https://github.com/info442-sp21/d-team/issues/70
