### ISSUE TITLE
Attending people go beyond spot limit[Major]

### ISSUE THREAD

**Issue by changz23-1836696** [info442-sp21/d-team#102]
**Describe the bug**
More people "attend" the event than the capacity of that event

**To Reproduce**
1. Go to 'Your events'
2. Click on 'Detail' of an event card
3. Click on 'Attend' of an event card'
4. Attending people go off-limit

**Expected behavior**
Spot letting users attend event if the event is full

**Actual behavior**
User can still add a least one attendance even if the event is full

**Screenshots**
![image](https://user-images.githubusercontent.com/43832007/119601668-7af08e80-bd9e-11eb-88b2-c096138ac176.png)

**Desktop (please complete the following information):**
OS: Windows10
Browser Chrome
Version 90.0.4430.212

**Comment by ashshah1** [comment]
This is a duplicate bug, we will be addressing the original one here: https://github.com/info442-sp21/d-team/issues/67

**Comment by cherimarie** [comment]
For grading purposes, I won't be counting this as a duplicate, but for issue organization it's fine if you do.

**Comment by cherimarie** [comment]
This is a minor bug, not major.
