### ISSUE TITLE
Notification disappearance 

### ISSUE THREAD

**Issue by waheedahakim** [info442-sp21/d-team#110]
**Describe the bug**
when you delete an event there is a notification that asks if you want to still delete the event, even if you click yes it will do the job but the notification wont go away unless you close out of it.

**To Reproduce**
1. Go to events
2. click on cancel event
3. then chose yes
4. you will notice the notification stays on

**Expected behavior**
once you click on yes or no for event cancellation the pop up notification should go away.

**Screenshots**
![image](https://user-images.githubusercontent.com/43686537/120366016-fdf47600-c2c3-11eb-856f-a734e9fedfae.png)

**Desktop (please complete the following information):**
 - Browser [e.g. chrome]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kristina-te** [comment]
Duplicate issue and comments on issue can be found here: https://github.com/info442-sp21/d-team/issues/74. In addition, issue has been resolved.
