### ISSUE TITLE
Quiz

### ISSUE THREAD

**Issue by waheedahakim** [info442-sp21/d-team#112]
**Describe the bug**
The quiz probably have more questions but after i select my answer for the first question there is no button or clue to take users forward to the next question.

**To Reproduce**
1. Go to 'the home page'
2. Click on the quiz
3. Scroll down to select answer for question 1
4. look for a button to move forward

**Expected behavior**
there should be a button to click on to take you to other questions like "Next" 

**Screenshots**

**Desktop (please complete the following information):**
 - Browser [ chrome]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by smckissick1** [comment]
While this is a good suggestion, the "Add Event" page is a form that we believe is important to see all parts of the form at once, not one at a time (also this is not a quiz). For these reasons, we won't pursue a change.
