### ISSUE TITLE
Event Details

### ISSUE THREAD

**Issue by waheedahakim** [info442-sp21/d-team#114]
**Describe the bug**
once a person creates an event there is no way at least a clear way to go back and click on the event to see event details so it is easy to forget.
**To Reproduce**
1. Go to create event
2. Click on create event
3. Scroll down to the form and fill out the information
4. See error on the your event page 

**Expected behavior**
 users should be able to go back and check event details anytime

**Screenshots**
![image](https://user-images.githubusercontent.com/43686537/120710504-11920f00-c473-11eb-8045-3335456a585b.png)

**Desktop (please complete the following information):**
 - Browser [e.g. chrome]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by smckissick1** [comment]
This was originally labeled a bug, but our design choice to show all event details in the "Your Events" page would indicate that this is more of an enhancement suggestion (details about events you're hosting can also be found in the newsfeed). We believe that the event details are easily enough accessed and will not be moving forward with this suggestion.
