### ISSUE TITLE
[Major] When "Attending" button is clicked more than once, the attendee spots keep incrementing

### ISSUE THREAD

**Issue by yiuchungcheung** [info442-sp21/d-team#67]
**Describe the bug**
After you sign up to participate in an event, if you click attending again it adds another spot to the attendance so it keeps filling up the spots if you keep clicking 'attending'.

severity: Major

**To Reproduce**
1. log in
2. Click on 'view details' on any event
3. Click "participate in event"
4. Click "attending" more than once
4. See error (the attendees keep incrementing)

**Expected behavior**
attendance spots should not be incrementing as you will only be attending once for the event you signed up for.

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Browser: Chrome
 - Version 90.0.4430.212

**Comment by sienasc** [comment]
To add on to this, I think it would be beneficial if you click the attending button it puts it back to "Participate in Event". Then you wouldn't have to go to "Your Events" tab and click the x button and then confirm. It's just less steps

**Comment by smckissick1** [comment]
This will be fixed in the next sprint by disabling the attending button upon clicking once.

**Comment by ashshah1** [comment]
Bug has been fixed: https://github.com/info442-sp21/d-team/commit/67f6592abe87ac852b4fa8c2080a8f76247cbad6

**Comment by cherimarie** [comment]
I think this is a minor issue, not major, so it won't be counted against D Team's HW6.
