### ISSUE TITLE
[Major] "Flag As Inappropriate" button doesn't give feedback after clicked on

### ISSUE THREAD

**Issue by yiuchungcheung** [info442-sp21/d-team#68]
**Describe the bug**
The 'flag as inappropriate' button currently isn't doing anything after you click on it(?)

severity: Major 

**To Reproduce**
1. Login
2. Click on 'view details' on any event
3. Click on 'flag as inappropriate'
4. See error (no feedback/interaction given)

**Expected behavior**
There should be at least some feedback when clicking on the button, such as a pop-up saying you have "flagged" the event or change the visualization of the button after it is clicked. 

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Browser Chrome
 - Version 90.0.4430.212

**Comment by ashshah1** [comment]
We made a design choice to not give feedback on clicking the "flag button" so we'd consider this an enhancement request not a bug. This won't be edited in our next development sprint.

**Comment by cherimarie** [comment]
This is a major bug. The flags are presented to users as a feature that can be used, they should either work or not be shown. I think what "working" would look like (at a minimum) is: saving that attribute of "flagged" on the event, having the flag icon appear as an outline with text of "flag as inappropriate" if "flagged" is false, having icon appear solid with text of "this even has been flagged as inappropriate" if "flagged" is true. Full implementation would be more complex, but this seems like a possible MVP of this feature.

(Apologies if I posted this on a different issue already- I'm only counting it as a single major bug, but maybe it was reported twice)

**Comment by ashshah1** [comment]
This issue has been closed, the flag as inappropriate buttons now visually changes upon being clicked, in addition to updating the database https://github.com/info442-sp21/d-team/commit/db7dda61bc65dcc5eb714f9f7b02af8807348785
