### ISSUE TITLE
[Minor] Event can be made with invalid event details 

### ISSUE THREAD

**Issue by yejukim** [info442-sp21/d-team#70]
An event can be hosted by putting invalid details in the text fields. For instance, the zip code can be made of characters instead of numbers) and the maximum amount of people can be a negative number.

1. Click Host an Event
2. Put random characters into zip code field

Expected Result: 
"Invalid zip code" 
Actual:
Checkmark that it goes through

Environment: Chrome 90.0.4430.93 on macOS (Mojave)

**Comment by kmarshall98** [comment]
An event can be hosted by putting invalid details in the text fields. This applies to other fields as well. Specifically the most concerning being invalid times. For example a user could put a time that doesn't specify AM or PM, a different day or end time that is after the start time, and a date that has already passed.

Severity: Major

<img width="869" alt="Screen Shot 2021-05-25 at 2 31 36 PM" src="https://user-images.githubusercontent.com/46639384/119571203-ea965780-bd65-11eb-818f-b4c5d14abeec.png">

Environment: Safari on macOS Big Sur Version 11.2.3

**Comment by ashshah1** [comment]
This bug will be fixed in the next development sprint.

**Comment by ashshah1** [comment]
Additional form validation parameters have been set, https://github.com/info442-sp21/d-team/commit/77f884d4c09749dff9d1343f40930da3f75efffd and https://github.com/info442-sp21/d-team/commit/6f16e27c241cd381d3f0b2e90b8a04aa0d2e3db5
