### ISSUE TITLE
Event appears blank [Minor]

### ISSUE THREAD

**Issue by sienasc** [info442-sp21/d-team#71]
**Describe the bug**
When I logged in, the first page you see with the events I saw an event and it was completely blank for me. I attached a picture bellow.

**To Reproduce**
1. Go to the home/main page
2. It is the first event for me. I'm not sure if it's because of my location. Maybe you guys could have an about page. I'm not really sure what the website is for.

**Expected behavior**
I would expect this card to look like the rest: have a title, image, place, and date. This one has a comma, and a view details button.

**Screenshots**
<img width="774" alt="Screen Shot 2021-05-25 at 2 12 18 PM" src="https://user-images.githubusercontent.com/63016712/119569160-38f62700-bd63-11eb-9a2e-05c53c354b78.png">

Desktop (please complete the following information):

OS: iOS 11.2.1
Browser: Safari
Version: Version 14.0.3 (16610.4.3.1.4)

**Comment by ashshah1** [comment]
We don't consider this a bug, someone created a blank event and thus the card was created as such. They chose to not upload an image and therefore the card looks different than some of the others.

**Comment by cherimarie** [comment]
I'd consider this a bug, as post validation is not sufficient. Users shouldn't be able to create posts like this. I believe there's already a ticket for post validation.
