### ISSUE TITLE
[Minor] Scheduled Time on Host Event allows end time to be before start time

### ISSUE THREAD

**Issue by jordanjones243** [info442-sp21/d-team#72]
**Describe the bug**
When hosting an event, you need to put details about the event down. One of the details that is needed to be provided is the start and end time of your event. The bug here is that when putting the start and end times of the event, I was able to successfully set the start time to 9:15pm and the end time to to 9pm.

**To Reproduce**
1. Sign in
2. Go to Host an Event
3. Fill in information about the event, including start and end time.
4. Submit form.

**Expected behavior**
The expected behavior is for the form to be submitted (which it is able to be), but when someone puts a start time that is later than the end time, an error message should pop up or the form should not be able to be submitted.

**Desktop (please complete the following information):**
Google Chrome Version 89.0.4389.128 (Official Build) (x86_64)

**Comment by ashshah1** [comment]
This is a duplicate bug, here is the original issue that we will be addressing: https://github.com/info442-sp21/d-team/issues/70

**Comment by cherimarie** [comment]
For Jordan's grade, I won't consider this as a duplicate, though for issue organizing it's fine to do so.
