### ISSUE TITLE
Add event descriptions on home page under event

### ISSUE THREAD

**Issue by drishtividyarthi** [info442-sp21/d-team#73]
It might enhance the user experience if you guys added small event descriptions in the event boxes on the home page so the user can see more specifically what the time commitment would be or what they would have to do at the event without having to click into the event box. This idea would be useful if the team decides to stick with the linear, one event box, scrolling display.

Another thing would be to change the display of the events so it's more like a grid and that way users don't have to scroll as much and they can see all the events at once. In this display it might be better not to add the descriptions because the event boxes would be smaller but the user can see more at once and it would minimize scrolling and searching effort. 

I think either one of these enhancements might support the user experience as they don't have to spend as much effort searching for an event that would be useful for them to attend. They could see information they need more quickly and more easily. This is a simple design suggestion, but it could improve the overall usability of the app and make the flow smoother.

**Comment by ashshah1** [comment]
We are not going to incorporate this enhancement, we think the "View Details" button is a fairly short and quick way to get to more details about the event and we think a simple event card is a design choice we want to stick with.
