### ISSUE TITLE
[Minor] Attendance cancellation pop up does not close

### ISSUE THREAD

**Issue by mariamatlick** [info442-sp21/d-team#74]
**Describe the bug**
When you are under the “Your Events” tab and hit the “X” on one of your events, the pop up does not automatically close when you click “Yes” or “No”, but once you click one of these the pop up is now for your next listed event (although nothing indicates this and you didn’t purposefully try to rescind attendance for that event)

**To Reproduce**
1. Make account
2. Add attendance to at least 2 events
3. Go to “Your Events” tab
4. Click “X” on one of the events
5. Click “Yes” I want to cancel attendance
6. See error: Event is removed (other event is still there), but box stays open 
7. Click “Yes” I want to cancel attendance
8. See error: Second event is also removed

**Expected behavior**
Click “yes” or “no” and pop up closes

**Actual Result**
Pop up stays open, no indication that you are now editing attendance for one of your other events

**Desktop (please complete the following information):**
 - OS: Windows 10.0.19041 Build 19041
 - Browser: Chrome Version: Version 90.0.4430.212 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

**Comment by ashshah1** [comment]
This will be fixed in the next development sprint.

**Comment by ashshah1** [comment]
Bug has been fixed: https://github.com/info442-sp21/d-team/commit/67f6592abe87ac852b4fa8c2080a8f76247cbad6
