### ISSUE TITLE
Events Don't Filter for Low, Medium & High Level of Committments

### ISSUE THREAD

**Issue by juliashull** [info442-sp21/d-team#75]
**Describe the bug**
When I click or unclick the level of commitment check boxes, the events show do not change.

**To Reproduce**
1. Go to home page
2. Click on either Low, Medium or High check boxes
3. See how events shown do not change

**Expected behavior**
Expected to see the page refresh and only show specific events with that particular label on it. 

**Desktop (please complete the following information):**
 - Chrome
 - Windows laptop

**Comment by ashshah1** [comment]
This is a duplicate issue and we will be addressing the original, linked here: https://github.com/info442-sp21/d-team/issues/69
