### ISSUE TITLE
[Enhancement] About Us Page

### ISSUE THREAD

**Issue by yejukim** [info442-sp21/d-team#76]
It would be a nice feature to have an about page for your website! 
I think it would be helpful for the users to understand what to use your website for and what you can do with your website features.

**Comment by ashshah1** [comment]
We will be incorporating this enhancement into our next version.

**Comment by kristina-te** [comment]
The about page is created with the commit [https://github.com/info442-sp21/d-team/commit/b2bea03566fccdadfc49de6c5844502427b5fa25](url).
