### ISSUE TITLE
[Minor] When opening up website on mobile device, header doesn't adjust to screen

### ISSUE THREAD

**Issue by bphan23** [info442-sp21/d-team#77]
* Severity - Major
* When uploaded the website on a mobile device, the navbar was out of the page. Only half of the navbar was shown, to see the rest half to scroll over.
* Used - Safari on the iPhone 11
* CSS styling to make the navbar readjust on smaller devices.
* Navbar is showing only 1/2 of itself, to see the rest have to scroll over.
* Expected to be able to see everything I see when opening in on a desktop or laptop.

**Comment by kristina-te** [comment]
This is important for future development work on Demeter to make it accessible and we recognize a large number of users would be accessing our application on mobile. However, for the initial iterations of Demeter until we truly scale, we will not focus on mobile development and will focus on desktop experiences. Thus, we will not be implementing this enhancement.
