### ISSUE TITLE
[Enhancement] No Page Title + Fav Icon in Browser Tab

### ISSUE THREAD

**Issue by mariamatlick** [info442-sp21/d-team#78]
Currently, there is the default "React App" title and fav icon visible in the browser tab.
Feature Request: Change this page title to be "Demeter" with your logo as the fav icon
Useful: This would be useful so you know what website you have open and can quickly navigate to it. It also helps searchers recognize your website in search results
![image](https://user-images.githubusercontent.com/49167660/119570319-ce45eb00-bd64-11eb-9790-b69fbf39cb75.png)

**Comment by ashshah1** [comment]
This is something we will add to our next deployment.

**Comment by smckissick1** [comment]
This issue has been fixed, the generic "React App" title has been changed to match the rest of our site here: e48aeddac4871e5d3c9be4d6bd1f9f6a624d5d82
