### ISSUE TITLE
[Minor] The title of the pop up after submitting a new event has not been changed from Modal placeholder

### ISSUE THREAD

**Issue by dorilusions** [info442-sp21/d-team#79]
After submitting an event, what I'm assuming is the placeholder title for the conformation popup has not been changed and is still called "Modal Title".

1. Go to 'Host an Event'
2. Fill out the form
3. Click 'Submit'

**Expected behavior**
I would expect the modal title to be relevant to the confirmation message.

**Screenshots**
![image](https://user-images.githubusercontent.com/43550545/119571789-a5bef080-bd66-11eb-9013-a7de248d3777.png)

**Desktop**
 - Google Chrome
 - Version 90.0.4430.212

**Comment by ashshah1** [comment]
This will be fixed in the next deployment of our app.

**Comment by ashshah1** [comment]
Bug has been fixed: https://github.com/info442-sp21/d-team/commit/67f6592abe87ac852b4fa8c2080a8f76247cbad6
