### ISSUE TITLE
Delete account confirmation page

### ISSUE THREAD

**Issue by ndemmel** [info442-sp21/d-team#80]
**Describe the request*
I would like to request a feature that informs the user of what will happen to their account after they click the 'delete account' button on the profile page. I clicked the button and saw my profile picture disappear, and then when I navigated back to the home page I was instantly logged out.

Giving users some kind of message about the consequences and immediate actions that will occur after they delete their account would help people make more informed choices when considering to terminate their account. This message could also serve as a safeguard for situations where people accidentally press the 'delete account' button.

**Comment by ashshah1** [comment]
We have decided not to incorporate this enhancement given the remaining time in our development sprint. We want to focus on other more important features and bug fixes at this time.
