### ISSUE TITLE
[Major] Post details not showing

### ISSUE THREAD

**Issue by atnguyenduy** [info442-sp21/d-team#81]
**Describe the bug**
Details of top post is not showing

**To Reproduce**
1. Go to 'https://demeter-uw.web.app/'
2. Scroll to first post
4. See content error in first post

**Expected behavior**
Expected to see top post similar to rest of bottom posts

**Screenshots**
![image](https://user-images.githubusercontent.com/41980535/119572047-05b59700-bd67-11eb-8521-d3e68f21ce3a.png)

**Desktop (please complete the following information):**
Device: Lenovo Thinkpad laptop
Windows 10 Enterprise / Version 20H2 / OS build 19042.804
Browser: Edge

**Comment by ashshah1** [comment]
This is an invalid issue, we've explained the rationale here: https://github.com/info442-sp21/d-team/issues/71

**Comment by cherimarie** [comment]
Agreed, this is invalid, not major.
