### ISSUE TITLE
[Minor] The log in page has the sign in button and the background image cut off from the page

### ISSUE THREAD

**Issue by tichx** [info442-sp21/d-team#82]
**Describe the bug**
The sign-in button and the background image on the mobile screen were not well-designed. Currently, the sign-in button was off the screen.

**Severity**
Minor

**To Reproduce**
1. Go to the website
2. On the very first page, you will see

**Expected behavior**
The sign-in button fits nicely into the page, perhaps at the center of the screen. The background image is appropriately stretched to fit in the screen.

**Current behavior**
The button is to the edge of the screen, and users need to swipe to find it. The background image only showing a small tip at the bottom of the page.

**Screenshots**
![IMG_88E9AD164564-1](https://user-images.githubusercontent.com/12144060/119572442-942a1880-bd67-11eb-862e-eee5388328a0.jpeg)

**Mobile (please complete the following information):**
 - OS: iOS
 - Browser: Safari
 - Version: V.14
 - Device: iPhone 12 Pro Max

**Comment by kristina-te** [comment]
This is important for future development work on Demeter to make it accessible and we recognize a large number of users would be accessing our application on mobile. However, for the initial iterations of Demeter until we truly scale, we will not focus on mobile development and will focus on desktop experiences. Thus, we will not be implementing this enhancement. 
https://github.com/info442-sp21/d-team/issues/77

**Comment by kristina-te** [comment]
Completed with commit https://github.com/info442-sp21/d-team/commit/bdbbdc144f01cceef9ef8051065f8e3c505756d5. Should now render properly on mobile for landing page.
