### ISSUE TITLE
[Minor] Some elements of the event form clear after submitting a new event while others do not

### ISSUE THREAD

**Issue by dorilusions** [info442-sp21/d-team#83]
**Describe the bug**
After submitting a new event, certain elements such as the address and city line clear while others such as the time, date, and maximum attendee fields do not and remain from the previous event entry.

**To Reproduce**
1. Go to 'Host an Event'
2. Fill out the form
3. Click 'Submit' and close the popup.
4. See that the address/city have reset but other fields have not.

**Expected behavior**
For the entire form to be cleared and be ready for a new event entry.

**Desktop (please complete the following information):**
 - Chrome
 - Version 90.0.4430.212

**Comment by ashshah1** [comment]
We are not going to address this bug, we recognize that this is an issue but do not think it detract from the app's core functionality.
