### ISSUE TITLE
[Minor] The first event listed is miscellaneous with a broken image 

### ISSUE THREAD

**Issue by RaphaelKyle** [info442-sp21/d-team#84]
**Describe the bug**
The first event listed is "090 -08 i00 , WA 0099-08-07 at 14:08 Commitment: low" with a broken image path with an alt text "event image". I'm not sure if this was meant to be there or a remnant of a test/debugging process. 
 
**To Reproduce**
1. Login with Google 
2. Go to the Home page

**Expected behavior**
All the events make sense with a nice picture like the other events on the Home page

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS Big Sur (11.4)
 - Browser: Chrome
 - Version: 91.0.4472.77 (Official Build) (x86_64)

**Additional context**

**Comment by ashshah1** [comment]
This is a duplicate issue, that was marked as invalid: https://github.com/info442-sp21/d-team/issues/71
