### ISSUE TITLE
Enhancement: Add ability to link or add event to google calendar

### ISSUE THREAD

**Issue by drishtividyarthi** [info442-sp21/d-team#87]
It might be helpful if there was a way to add the event to the user's google calendar, when the user saves it. Another possibility is to allow the user to link their google calendar and filter events based on their own availability. This way the user can both see events when they are available and to add events to their own calendar. 

This would help users keep track of their own busy schedules while also helping them find time to attend these important events. Including this feature would help the user that the developers understand everyone has very busy lives and are still doing their best to help the user make time for these important events and actually motivate the user more to participate.

**Comment by ashshah1** [comment]
This is an enhancement that we don't believe is possible within the remaining time frame of this project so we will not be adding it into our next deployment.
