### ISSUE TITLE
Add manual sign in

### ISSUE THREAD

**Issue by haileymeister** [info442-sp21/d-team#88]
It would be nice to have a manual email and password sign in so that if a user does not want to link to their gmail account or they do not have one they can still use the application. You can do this through firebase and isn't too challenging to get working.

**Comment by ashshah1** [comment]
We will not be incorporating this change. We think the Google authentication is an easier sign in method and if users feel like they don't want to have their account associated with the app any longer, we have a delete account feature that deletes all the users' data stored in our backend.
