### ISSUE TITLE
Mobile Navigation [minor]

### ISSUE THREAD

**Issue by brendantran** [info442-sp21/d-team#89]
**Describe the bug**
The right 2 nav elements on the navbar are hidden when on a smaller screen.

**To Reproduce**
1. Go to any page with the navbar
2. Change screen resolution to be the smallest possible
3. The right two nav elements are covered.

**Expected behavior**
Be able to easily find the entire navbar.

**Desktop (please complete the following information):**
 - OS: MacOS Big Sure
 - Browser: Chrome
 - Version 90.0.4430.93 (Official Build) (x86_64)

**Comment by kristina-te** [comment]
This is important for future development work on Demeter to make it accessible and we recognize a large number of users would be accessing our application on mobile. However, for the initial iterations of Demeter until we truly scale, we will not focus on mobile development and will focus on desktop experiences. Thus, we will not be implementing this enhancement. 
https://github.com/info442-sp21/d-team/issues/77
