### ISSUE TITLE
[Minor] Show which NavLink is active

### ISSUE THREAD

**Issue by haileymeister** [info442-sp21/d-team#90]
It is very helpful to highlight the current page link you are on so that the user doesn't get lost in the website.

**Comment by ashshah1** [comment]
This is something we'll fix in the next deployment of our app.

**Comment by smckissick1** [comment]
This enhancement suggestion has been completed; the user's current page is now shown with an underline in the nav bar. The commit can be found here: https://github.com/info442-sp21/d-team/pull/107/commits/e9e481fed7309b7d16a2b252e73e35f52c36c981
