### ISSUE TITLE
[Minor] Clicking on your user profile picture and going back logs you out 

### ISSUE THREAD

**Issue by popi1141** [info442-sp21/d-team#91]
**Describe the bug**
When exiting the page, even when on an internal link, you get logged out. You have to press the 'Continue with Google Account' to come back in. Sometimes it logs you back in automatically. 

**To Reproduce**
1. Go to / Log in to any part of the website. 
2. Go to Profile and Click on Your Profile Picture
3. Go Back to the Previous Page
4. You'll Be Logged Out. Waiting for a bit logs you back in, but sometimes it just makes you have to click 'Continue With Google' again.

**Expected behavior**
Typically expect that your session will persist. 

**Screenshots**
https://www.loom.com/share/d50d8adf59834636a60c6548a06e51a3

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Microsoft Edge

**Comment by ashshah1** [comment]
This is a bug that will be addressing in our next deployment of the app.

**Comment by smckissick1** [comment]
This bug has been fixed by disabling the profile picture so that it is no longer clickable. You can find the commit here: https://github.com/info442-sp21/d-team/pull/106/commits/685fc22fea7675ad3ea4b2a9174e1369142ebcc7
