### ISSUE TITLE
[Enhancement] Option to go to home page or refresh page when logo is clicked on

### ISSUE THREAD

**Issue by yiuchungcheung** [info442-sp21/d-team#92]
description of the requested feature: adding clickable functionality to the logo so it can navigate back to/refresh home page.
explanation for why it would be useful: It would just be a handy shortcut for users to want to quickly navigate to/refresh the home page.

**Comment by ashshah1** [comment]
This is something we can address in the next deployment of our app, we agree it would be more intuitive to have the logo be clickable and redirect to home.

**Comment by ashshah1** [comment]
Enhancement has been implemented: https://github.com/info442-sp21/d-team/commit/cb204e4d880507fcc9f1fe999a6c97b0cec27d69
