### ISSUE TITLE
Feature enhancement: add homepage description 

### ISSUE THREAD

**Issue by abq14** [info442-sp21/d-team#94]
On the homepage, there's no description of what this page entails and the first event that's displayed isn't very descriptive, so I wasn't sure what I was supposed to be looking at. I didn't even realize I was able to scroll. I suggest adding some description that says "View community events" on the top of the homepage. This would help users understand what they're supposed to be looking at on this page. 

![image](https://user-images.githubusercontent.com/30161847/119593662-34dffe80-bd8f-11eb-8e8c-da3d2e4fcb20.png)

**Comment by ashshah1** [comment]
This is a duplicate enhancement request that we will be incorporating in the next deployment: https://github.com/info442-sp21/d-team/issues/76

**Comment by cherimarie** [comment]
For grading purposes, I won't consider this a duplicate, but for issue organization it's fine to.
