### ISSUE TITLE
Feature enhancement: Homepage adding number of events

### ISSUE THREAD

**Issue by abq14** [info442-sp21/d-team#95]
On the homepage, I didn't realize I was able to scroll. The event cards are quite big, so I suggest either shrinking the cards or adding the number of events that are in the database. This will make it more obvious that more events are on the site. The latter I think is an easier and quicker solution to implement. You could implement this by just writng "32 events avaiable" under the filter. 
![image](https://user-images.githubusercontent.com/30161847/119594097-ff87e080-bd8f-11eb-8658-185a5874d5b9.png)

**Comment by ashshah1** [comment]
We feel like it is fairly intuitive to scroll on a newsfeed type page so we likely will not be incorporating this enhancement. We could shrink the event cards to make this more seamless.
