### ISSUE TITLE
[Minor] User can participate in an event even if the date has passed

### ISSUE THREAD

**Issue by ifrahm** [info442-sp21/d-team#96]
The user is able to participate in an event that is dated in the past. 

**To Reproduce**
1. Log in 
2. Click Home 
3. Scroll down to 'nikkis cool event'
4. User can select "participate in event" 

 Mac Os Big Sur, Chrome

**Expected**
User being unable to participate in an event dated in the past, expected button or event card to be disabled to stop user from planning to attend.

**Actual behavior**
User can select "participate in event" and event the event will appear in the "Your event Events" page in the attending section

**Comment by ashshah1** [comment]
This is something we will fix in our next deployment of the app.

**Comment by ashshah1** [comment]
Bug has been fixed: https://github.com/info442-sp21/d-team/commit/cb204e4d880507fcc9f1fe999a6c97b0cec27d69
