### ISSUE TITLE
Enhancement: Add small image to the events listed  under Attending

### ISSUE THREAD

**Issue by ifrahm** [info442-sp21/d-team#97]
In the "Your Events" page, the events the user is attending is listed Attending with the date and more details button. I would suggest to display a small image if the event has an image . This would allow the user to get a better sense of what the event is without having to click on more details.

**Comment by ashshah1** [comment]
We think the "Details" button is a fairly quick way to view more information about an event and think that adding text information would make the page more crowded, so we will not be incorporating this change.
