### ISSUE TITLE
Unable to "Un-attend" an event

### ISSUE THREAD

**Issue by gidchia** [info442-sp21/d-team#99]
**Describe the bug**
Clicking the attend button displays a green "Attending" button. However, if I re-click it, it doesn't remove me from the event's attendance. Instead, it assumes I want to join the event with more than 1 pax.

**To Reproduce**
1. Go to an event card
2. Click on 'I'm attending'
3. Try to remove yourself from an event's attendance
4. See participant number increase

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser - Chrome
 - Version - Version 90.0.4430.85

**Additional context**

**Comment by changz23-1836696** [comment]
I find the un-attend event feature on the "Your events" page. You can un-attend by clicking the "cross" button on the right of each card.

**Comment by ashshah1** [comment]
Echoing the previous comment, users can un-attend events by canceling their attendance on the "Your Events" page.
